Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "gin")
Ingredient.create(name: "rhum")
Ingredient.create(name: "champagne")
Ingredient.create(name: "orange juice")
Ingredient.create(name: "tia maria")
Ingredient.create(name: "campari")
Ingredient.create(name: "wodka")
Ingredient.create(name: "ricard")
Ingredient.create(name: "cherry")
Ingredient.create(name: "whiskey")
Ingredient.create(name: "white wine")
Ingredient.create(name: "salt")
Ingredient.create(name: "brandy")
Ingredient.create(name: "coffee")
Ingredient.create(name: "water")
Ingredient.create(name: "sherry")
Ingredient.create(name: "tequila")
Ingredient.create(name: "tea")
Ingredient.create(name: "milk")
Ingredient.create(name: "amaretto")
Ingredient.create(name: "port")
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
